stereo_vis_odom:
  topics:
    img0: "/kitti/camera_gray_left/image_raw"
    img1: "/kitti/camera_gray_right/image_raw"

  orb:
    nfeatures: 1500
    scaleFactor: 1.2
    nlevels: 1
    edgeThreshold: 31 
    firstLevel: 0
    WTA_K: 4
    scoreType: 0
    patchSize: 31
    fastThreshold: 7 

  bf:
    normType: 7 
    crossCheck: True

  filters:
    StereoGeometry:
      max_u: 100.0
      min_u: 3.0 
      max_v: 3.0

  solvePnPRansac:
    useExtrinsicGuess: False
    iterationsCount: 100
    reprojectionError: 2.0
    confidence: 0.99
    flags: 2

  stereoCalibration:
    size:
      Width: 1226
      Height: 370

    matrixProjection:
      mp0:
        [
          718.856,
          0.0,
          607.1928,
          0.0,
          0.0,
          718.856,
          185.2157,
          0.0,
          0.0,
          0.0,
          1.0,
          0.0,
        ]
      mp1:
        [
          718.856,
          0.0,
          607.1928,
          -386.1448,
          0.0,
          718.856,
          185.2157,
          0.0,
          0.0,
          0.0,
          1.0,
          0.0,
        ]
